repository_type: pipeline

nf_core_version: 3.5.2

lint:
  files_unchanged:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-staphit2_logo_light.png
    - docs/images/nf-core-staphit2_logo_light.png
    - docs/images/nf-core-staphit2_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
    - assets/email_template.txt
    - docs/README.md
    - .gitignore            # repo-specific ignores (results, work dirs, data) on top of the template
  nextflow_config:
    - manifest.name
    - manifest.homePage
  multiqc_config:
    - report_comment
  files_exist:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-staphit2_logo_light.png
    - docs/images/nf-core-staphit2_logo_light.png
    - docs/images/nf-core-staphit2_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml

template:
  org: alarawms
  name: staphit2
  description: MRSA genomic surveillance pipeline
  author: alarawms
  version: 1.0.0dev
  force: true
  outdir: staphit2
  is_nfcore: false
